#version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ~/.vw-data:/data
    environment:
      - DOMAIN=https://vault.grep2000.com # 建议设置
      - SIGNUPS_ALLOWED=false # 是否允许注册，建议关闭
    # ports:
    #   - "8080:80"         # 不建议直接暴露公网端口


    networks:
      - traefik_net # 如果想让 Traefik 直接访问容器，可以加这个网络


networks:
  traefik_net:
    external: true
