services:
  derper:
    image: ghcr.io/tailscale/derper:latest
    restart: always
    ports:
      - "8443:8443/tcp"    # DERP HTTPS
      - "3478:3478/udp"    # STUN
    volumes:
      - /root/.acme.sh/grep2000.com_ecc:/app/certs
    command: >
      /app/derper
      --hostname=derp.mysite.com
      --certmode=manual
      --certdir=/app/certs
      --a=:8443
      --stun=true
      --stun-port=3478
      --verify-clients=true
